QT.enginio.VERSION = 1.8.0
QT.enginio.name = Enginio
QT.enginio.module = Enginio
QT.enginio.libs = $$QT_MODULE_LIB_BASE
QT.enginio.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/Enginio
QT.enginio.frameworks =
QT.enginio.bins = $$QT_MODULE_BIN_BASE
QT.enginio.depends = core network
QT.enginio.uses =
QT.enginio.module_config = v2
QT.enginio.DEFINES = QT_ENGINIO_LIB
QT.enginio.enabled_features =
QT.enginio.disabled_features =
QT_CONFIG +=
QT_MODULES += enginio
