#!/bin/sh

export PATH=/system/bin:/sbin:/bin:/usr/sbin:/usr/bin:$PATH
export LD_LIBRARY_PATH=/lib:/usr/lib:/system/lib:$LD_LIBRARY_PATH

mount -a
mkdir /dev/pts
mount -t devpts devpts /dev/pts

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

sysctl -w kernel.core_pattern=/var/log/%e.core.%p
insmod /lib/modules/binder.ko
